### ISSUE TITLE
添加新的地图投影：墨卡托(Mercator)投影，又称等角正切圆柱投影

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#53]
添加新的地图投影：墨卡托(Mercator)投影，又称等角正切圆柱投影

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-689295034_

**Comment by yelloxing** [comment]
@cldsx-it 认领

**Comment by hai2007** [comment]
当前已经有的地图算法已经足够使用了，后续如果有需要再丰富
