### ISSUE TITLE
### 获得颜色值

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#54]
### 获得颜色值

**返回一个颜色感觉的一系列颜色值，在寻求一个稳定，好看的计算方法。**

状态：讨论阶段

```js
// 获取一组色彩
export let getColors = num=> {
    let temp = [];
    for (let flag = 1; flag <= num; flag++)
        temp.push('rgb(' + (Math.random(1) * 230 + 20).toFixed(0) + ',' + (Math.random(1) * 230 + 20).toFixed(0) + ',' + (Math.random(1) * 230 + 20).toFixed(0) + ')');
    return temp;
};
```

这种随机获取的颜色可以使用，可是每次刷新页面以后就不一样了，不好，另外，具体的颜色调用也没办法有一定程度的控制。

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-528790151_

**Comment by yelloxing** [comment]
![屏幕快照 2020-09-09 14 21 19](https://user-images.githubusercontent.com/23074691/92561964-c7934880-f2a7-11ea-924b-3743cb977380.png)

**Comment by yelloxing** [comment]
@yelloxing  认领

**Comment by hai2007** [comment]
循环色的方法已经在实际中确定够用了

https://hai2007.gitee.io/image2d/#/api/tool?fixed=colors-getLoopColors
