### ISSUE TITLE
添加新的布局：force力布局

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#55]
添加新的布局：force力布局

![屏幕快照 2020-09-09 14 29 48](https://user-images.githubusercontent.com/23074691/92562733-0675ce00-f2a9-11ea-8eee-02cc3b9a1a81.png)

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-689337234_

**Comment by hai2007** [comment]
https://clunch-contrib.github.io/force-laboratory/

**Comment by hai2007** [comment]
力图的探索，迁移到新的项目，如果有了成果再考虑是否需要内置或独立提供

https://clunch-contrib.github.io/force-laboratory/
