### ISSUE TITLE
由于canvas和svg不同，无法很方便的为某个图形绑定交互事件，是否有好的解决方案。

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#56]
由于canvas和svg不同，无法很方便的为某个图形绑定交互事件，是否有好的解决方案。

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-689340200_

**Comment by chenyangkai12** [comment]
@chenyangkai12   @wyf46258

**Comment by yelloxing** [comment]
确定是否选择了一个区域，一个可行的方法是，使用一种颜色在空白的纸是绘制，然后根据画布中鼠标的位置来查看这张空白的纸上此次是否被特定颜色涂抹了，如果涂抹了，就说明鼠标位于当前选择的图形，反之没有。

**Comment by hai2007** [comment]
如果需要绑定可以试用svg绘制，虽然我们也可以为canvas提供区域管理，不过框架clunch已经有了类似的设计，目前就不考虑了，如果未来有必要再添加

https://hai2007.github.io/clunch/
