### ISSUE TITLE
添加新的布局：条形图布局

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#57]
添加新的布局：条形图布局

关于类似下面的图形，是否有类似tree或pie等的布局来方便我们绘制，虽然手动计算并不难。

![屏幕快照 2020-09-09 14 40 20](https://user-images.githubusercontent.com/23074691/92563705-8fd9d000-f2aa-11ea-8275-53b3eacaee91.png)

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-689341955_

**Comment by huxiangyang-0215** [comment]
@wangjun464

**Comment by hai2007** [comment]
布局过于简单，如果绘制方法不清楚，可以给我们留言，我们会通过文档的方式进行说明

https://hai2007.github.io/common-graphics-rendering-demonstration/
