### ISSUE TITLE
常见的坐标无非两种：直角坐标系和极坐标系。

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#58]
常见的坐标无非两种：直角坐标系和极坐标系，在绘制的时候，是否有好的方式提供一个简单的对象，通过配置以后，辅助计算实际绘制的（x,y），和地图类似。

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-689343716_

**Comment by miren-ruan** [comment]
@miren-ruan
@huxiangyang-0215

**Comment by yelloxing** [comment]
坐标系可以从两个方面进行考虑：1.数据到坐标的映射，2.各种刻度尺的绘制

如何很好的设计接口来满足这两点也很重要

**Comment by hai2007** [comment]
这里的思想我们已经在3d库中进行了实践，的确很好用，不过，当前项目的设计是基础绘图方法，不是图表库，目前看没有必要，如果有必要再，可能，我们未来更清晰开发一个独立的图表库或者别的来支持，而不是让当前项目过于冗余

https://hai2007.github.io/puly/
