### ISSUE TITLE
### 关于treeLayout布局

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#59]
目前树布局不够灵活，比如某个结点的删除或隐藏，树图动态改变，如何更好的孤独？是否需要image2D提供，需要进一步思考。

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-528292013_

**Comment by hai2007** [comment]
数据改变后，自己计算即可，每个结点有id，无需多余计算，后续如果需要再思考，当前认为新的改动意义不大
