### ISSUE TITLE
### 关于动画

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#60]
### 关于动画

**一方面：考虑是否在可能的时候使用浏览器原生动画方法**

**另一方面：动画控制接口是否可以更加灵活，比如快进，回退，暂停等操作**

状态：讨论阶段

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-528749671_

**Comment by hai2007** [comment]
当前认为，动画的本质是改变，我们已经在基础库提供了一个动画轮询方法，这里就不再提供了

https://hai2007.github.io/tool.js/#/api/animation?fixed=top
