### ISSUE TITLE
饼图布局

### ISSUE THREAD

**Issue by yelloxing** [hai2007/image2D#61]
和树图布局类似，是否需要在考虑数据改变的时候，优化动画，或者说，以后的布局都统一内置处理好动画。

我们需要进行一下讨论

_Originally posted by @yelloxing in https://github.com/yelloxing/image2D/issues/18#issuecomment-689549818_

**Comment by hai2007** [comment]
绘制方法在此说明，由于比较简单，不需要进行封装

https://hai2007.github.io/common-graphics-rendering-demonstration/#/ring?fixed=top
